### ISSUE TITLE
Metadata validation improvements

### ISSUE THREAD

**Issue by Vasantha-Kumar-J** [ni/measurement-plugin-python#25]
Add check to validate if the Display Name of the configuration/output set in python measurements contains special characters not supported by tag service. Also check on the UI Type Set properly

[AB#2267387](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2267387)

**Comment by dixonjoel** [comment]
@Vasantha-Kumar-J can you describe the user impact and / or add screenshots of what happens?

**Comment by Vasantha-Kumar-J** [comment]
@dixonjoel, We currently have validation in place for checking if the default value provided is matching the Data type of the parameter. This will enable the user to see an error before they start the measurement instead of runtime exceptions.
![image](https://user-images.githubusercontent.com/28588382/219036390-4dcdf68d-d4d1-4bc3-af8a-e457c327cf02.png)

Similarly, this issue was added since we wanted to add other validation to the metadata provided such as
- the display name is having invalid characters.
- the Instrument Type restriction provided for Pin Data type is unsupported.
- etc.
