### ISSUE TITLE
Complete MeasurementLink rebranding

### ISSUE THREAD

**Issue by jayaseelan-james** [ni/measurement-plugin-python#772]
## Tech Debt
Update the following files that reference the term MeasurementLink in one way or another.
1. [pyproject.toml](https://github.com/ni/measurement-plugin-python/blob/2be3bf58996751ea9e9d5fd6ecfd25011f361218/pyproject.toml#L14)
2. ~[README.md](https://github.com/ni/measurement-plugin-python/blob/2be3bf58996751ea9e9d5fd6ecfd25011f361218/README.md?plain=1#L43)~
3. [bug_report.md](https://github.com/ni/measurement-plugin-python/blob/2be3bf58996751ea9e9d5fd6ecfd25011f361218/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L48)
4. [examples\\.env.sample](https://github.com/ni/measurement-plugin-python/blob/2be3bf58996751ea9e9d5fd6ecfd25011f361218/examples/.env.sample#L5-L6)
5. [examples\\.env.simulation](https://github.com/ni/measurement-plugin-python/blob/2be3bf58996751ea9e9d5fd6ecfd25011f361218/examples/.env.simulation#L7-L8)
6. ~[examples\README.md](https://github.com/ni/measurement-plugin-python/blob/2be3bf58996751ea9e9d5fd6ecfd25011f361218/examples/README.md?plain=1#L41)~
7. [.measproj](https://github.com/ni/measurement-plugin-python/blob/2be3bf58996751ea9e9d5fd6ecfd25011f361218/ni_measurement_plugin_sdk_generator/ni_measurement_plugin_sdk_generator/templates/measurement.measproj.mako#L8) and [.measui](https://github.com/ni/measurement-plugin-python/blob/2be3bf58996751ea9e9d5fd6ecfd25011f361218/ni_measurement_plugin_sdk_generator/ni_measurement_plugin_sdk_generator/templates/measurement.measui.mako#L11) template files in the generator directory
8. [sample_measurement\\_stubs\color.proto](https://github.com/ni/measurement-plugin-python/blob/cc1d1881afeda94826c3dc746a613c9fb5896111/examples/sample_measurement/_stubs/color.proto#L7)
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

[AB#2783277](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2783277)

**Comment by jayaseelan-james** [comment]
Should we update the package name in the [color.proto](https://github.com/ni/measurement-plugin-python/blob/cc1d1881afeda94826c3dc746a613c9fb5896111/examples/sample_measurement/_stubs/color.proto#L7) under the .\examples\sample_measurement\\_stubs?

**Comment by dixonjoel** [comment]
> Should we update the package name in the [color.proto](https://github.com/ni/measurement-plugin-python/blob/cc1d1881afeda94826c3dc746a613c9fb5896111/examples/sample_measurement/_stubs/color.proto#L7) under the .\examples\sample_measurement\_stubs?

Yes, I think so.

**Comment by jayaseelan-james** [comment]
Update: Items 2 & 6 are taken care of as part of #837. 😃
