### ISSUE TITLE
game_of_life example uses incorrect serviceClass format

### ISSUE THREAD

**Issue by bkeryan** [ni/measurement-plugin-python#849]
# Bug Report

The serviceClass should look like a gRPC service name (with an optional _Python suffix), but the game_of_life example uses snake_case.

## Repro or Code Sample

https://github.com/search?q=repo%3Ani%2Fmeasurement-plugin-python%20serviceClass&type=code

## Expected Behavior

```
"serviceClass": "ni.examples.GameOfLife_Python",
```

## Current Behavior

```
"serviceClass": "game_of_life_Python",
```

## Possible Solution

Rename it and update the .measui

## Context

Measurement Client codegen derives module/class names from the service class.

## Your Environment

* OS & Device: Windows
* `ni-measurement-plugin-sdk-service` version: 2.1 main
* MeasurementLink version: 2024Q3
* Python version: 3.9

[AB#2841878](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2841878)

**Comment by dixonjoel** [comment]
@bkeryan This will break .sfp panels and other .measui files that people may already have. Are we ok with that?

**Comment by bkeryan** [comment]
> @bkeryan This will break .sfp panels and other .measui files that people may already have. Are we ok with that?

Yes. Examples are allowed to break compatibility.
