### ISSUE TITLE
Client generator is missing `--verbose` option

### ISSUE THREAD

**Issue by bkeryan** [ni/measurement-plugin-python#976]
# Bug Report

You should be able to specify `-v` or `-vv` to enable debug logging. The plugin generator and every example service has this but the client generator does not.

## Repro or Code Sample

```
ni-measurement-plugin-client-generator --all -v
```

## Expected Behavior

It enables info (-v) /debug (-vv?) logging.

## Current Behavior

```
Usage: ni-measurement-plugin-client-generator [OPTIONS]
Try 'ni-measurement-plugin-client-generator --help' for help.

Error: No such option: -v
```

## Context

Testing #966 

## Your Environment

* OS & Device: Windows
* `ni-measurement-plugin-sdk-service` version: 2.1.0 main
* MeasurementLink version: 25.0.0d71
* Python version: 3.9.13

[AB#2902967](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2902967)

**Comment by dixonjoel** [comment]
@bkeryan I don't know if this is a simple fix or not, but can we change it to tech debt so it's not on our 28d bug list?

**Comment by bkeryan** [comment]
It's a simple fix and I'd rather fix it.
